site_name: Dart for Visual Studio Code
collections:
  pages:
    output: true
    permalink: /:name
  releases:
    output: true
    permalink: /release/:name
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: _releases
      type: releases
    values:
      layout: release
